spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: project-A

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

server:
  servlet:
    session:
      timeout: 1h

app:
  mail:
    from: no-reply@voidcube.tech
    verification-subject: "Confirme seu e-mail - Project A"
  storage:
    images:
      max-size-bytes: 5242880
  
  messages:
    basename: messages
    enconding: UTF-8
    fallback-to-system-locale: false

