spring:
  profiles:
    active: dev
  application:
    name: project-A
server:
  servlet:
    session:
      timeout: 1h
app:
  mail:
    from: no-reply@voidcube.tech
    verification-subject: "Confirme seu e-mail - Project A"
